# /*******************************************************************************
#  * Copyright 2018 Dell Inc.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * @author: Jim White, Dell
#  * EdgeX Foundry, Edinburgh, version 1.0.0
#  * added: Jun 30, 2019
#  *******************************************************************************/

version: '3'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:
  portainer_data:
  vault-config:
  vault-file:
  vault-logs:

services:
  volume:
    image: edgexfoundry/docker-edgex-volume:1.0.0
    container_name: edgex-files
    network_mode: "host"
    volumes:
      - db-data:/data
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data

  consul:
    image: consul:1.3.1
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    image: edgexfoundry/docker-core-config-seed-go:1.0.0
    command: ["--profile=docker", "--cmd=/edgex/cmd-redis"]
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"

  vault:
    image: edgexfoundry/docker-edgex-vault:1.0.0
    container_name: edgex-vault
    hostname: edgex-vault
    network_mode: "host"
    ports:
      - "8200:8200"
    cap_add:
      - "IPC_LOCK"
    command: "server -log-level=info"
    environment:
      - 'VAULT_ADDR=https://edgex-vault:8200'
      - 'VAULT_CONFIG_DIR=/vault/config'
      - 'VAULT_UI=true'
    volumes:
      - vault-config:/vault/config
      - vault-file:/vault/file
      - vault-logs:/vault/logs
    depends_on:
      - volume
      - consul
    extra_hosts:
      - "edgex-vault:127.0.0.1"
      - "edgex-core-consul:127.0.0.1"

  vault-worker:
    image: edgexfoundry/docker-edgex-vault-worker-go:1.0.0
    container_name: edgex-vault-worker
    hostname: edgex-vault-worker
    command: ["--init=true", "--debug=false", "--wait=10", "--insureskipverify=false"]
    network_mode: "host"
    volumes:
      - vault-config:/vault/config
    depends_on:
      - volume
      - consul
      - vault
    extra_hosts:
      - "edgex-vault:127.0.0.1"
      - "edgex-core-consul:127.0.0.1"

# containers for reverse proxy
  kong-db:
    image: "postgres:9.6"
    container_name: kong-db
    hostname: kong-db
    network_mode: "host"
    ports:
        - "5432:5432"
    environment:
        - 'POSTGRES_DB=kong'
        - 'POSTGRES_USER=kong'
    extra_hosts:
      - "kong:127.0.0.1"

  kong-migrations:
    image: "kong:1.0.3"
    container_name: kong-migration
    hostname: kong-migration
    network_mode: "host"
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
    command: "kong migrations bootstrap"

  kong:
    image: "kong:1.0.3"
    container_name: kong
    hostname: kong
    network_mode: "host"
    ports:
        - "8000:8000"
        - "8001:8001"
        - "8443:8443"
        - "8444:8444"
    environment:
        - 'KONG_DATABASE=postgres'
        - 'KONG_PG_HOST=kong-db'
        - 'KONG_PROXY_ACCESS_LOG=/dev/stdout'
        - 'KONG_ADMIN_ACCESS_LOG=/dev/stdout'
        - 'KONG_PROXY_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_ERROR_LOG=/dev/stderr'
        - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
    depends_on:
        - kong-db
    extra_hosts:
      - "kong-db:127.0.0.1"

  edgex-proxy:
    image: "edgexfoundry/docker-edgex-proxy-go:1.0.0"
    container_name: edgex-proxy
    hostname: edgex-proxy
    network_mode: "host"
    volumes:
        - vault-config:/vault/config
    depends_on:
        - vault
        - kong-db
        - kong
    extra_hosts:
      - "edgex-vault:127.0.0.1"
      - "kong:127.0.0.1"
      - "kong-db:127.0.0.1"
# end of containers for reverse proxy

  redis:
    image: redis:5.0.5-alpine
    ports:
      - "6379:6379"
    container_name: edgex-redis
    hostname: edgex-redis
    network_mode: "host"
    volumes:
      - db-data:/data
    depends_on:
      - volume

  logging:
    image: edgexfoundry/docker-support-logging-go:1.0.1
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - config-seed
      - volume
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-redis:127.0.0.1"

  system:
    image: edgexfoundry/docker-sys-mgmt-agent-go:1.0.1
    ports:
      - "48090:48090"
    container_name: edgex-sys-mgmt-agent
    hostname: edgex-sys-mgmt-agent
    network_mode: "host"
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logging
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"

  notifications:
    image: edgexfoundry/docker-support-notifications-go:1.0.1
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging
      - redis
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"

  metadata:
    image: edgexfoundry/docker-core-metadata-go:1.0.1
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging
      - redis
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-redis:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"
      - "edgex-device-virtual:127.0.0.1"

  data:
    image: edgexfoundry/docker-core-data-go:1.0.1
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - logging
      - redis
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-redis:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"

  command:
    image: edgexfoundry/docker-core-command-go:1.0.1
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"

  scheduler:
    image: edgexfoundry/docker-support-scheduler-go:1.0.1
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - metadata
      - redis
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"

  export-client:
    image: edgexfoundry/docker-export-client-go:1.0.1
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-redis:127.0.0.1"
      - "edgex-export-distro:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"

  export-distro:
    image: edgexfoundry/docker-export-distro-go:1.0.1
    ports:
      - "48070:48070"
      - "5566:5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    environment:
      - EXPORT_DISTRO_CLIENT_HOST=export-client
      - EXPORT_DISTRO_DATA_HOST=edgex-core-data
      - EXPORT_DISTRO_CONSUL_HOST=edgex-config-seed
      - EXPORT_DISTRO_MQTTS_CERT_FILE=none
      - EXPORT_DISTRO_MQTTS_KEY_FILE=none
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-core-data:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"
      - "edgex-export-client:127.0.0.1"
      - "edgex-influxdb:127.0.0.1"

  rulesengine:
    image: edgexfoundry/docker-support-rulesengine:1.0.0
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    network_mode: "host"
    volumes:
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - export-client
    extra_hosts:
      - "edgex-core-consul:127.0.0.1"
      - "edgex-export-client:127.0.0.1"

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: edgexfoundry/docker-device-virtual-go:1.0.0
    ports:
    - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    network_mode: "host"
    volumes:
    - db-data:/data/db
    - log-data:/edgex/logs
    - consul-config:/consul/config
    - consul-data:/consul/data
    depends_on:
    - data
    - command
    extra_hosts:
      - "edgex-device-virtual:127.0.0.1"
      - "edgex-core-consul:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"
      - "edgex-core-metadata:127.0.0.1"
      - "edgex-core-data:127.0.0.1"

  device-random:
    image: edgexfoundry/docker-device-random-go:1.0.0
    ports:
      - "49988:49988"
    container_name: edgex-device-random
    hostname: edgex-device-random
    network_mode: "host"
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
      - command
    extra_hosts:
      - "edgex-device-random:127.0.0.1"
      - "edgex-core-consul:127.0.0.1"
      - "edgex-support-logging:127.0.0.1"
      - "edgex-core-metadata:127.0.0.1"
      - "edgex-core-data:127.0.0.1"

  # device-mqtt:
  #   image: edgexfoundry/docker-device-mqtt-go:1.0.0
  #   ports:
  #     - "49982:49982"
  #   container_name: edgex-device-mqtt
  #   hostname: edgex-device-mqtt
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  # device-modbus:
  #   image: edgexfoundry/docker-device-modbus-go:1.0.0
  #   ports:
  #     - "49991:49991"
  #   container_name: edgex-device-modbus
  #   hostname: edgex-device-modbus
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command
  #
  # device-snmp:
  #   image: edgexfoundry/docker-device-snmp-go:1.0.0
  #   ports:
  #     - "49993:49993"
  #   container_name: edgex-device-snmp
  #   hostname: edgex-device-snmp
  #   networks:
  #     - edgex-network
  #   volumes:
  #     - db-data:/data/db
  #     - log-data:/edgex/logs
  #     - consul-config:/consul/config
  #     - consul-data:/consul/data
  #   depends_on:
  #     - data
  #     - command

#################################################################
# UIs
#################################################################
  ui:
    image: edgexfoundry/docker-edgex-ui-go:1.0.0
    ports:
      - "4000:4000"
    container_name: edgex-ui-go
    hostname: edgex-ui-go
    network_mode: "host"
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - data
      - command

#################################################################
# Tooling
#################################################################

  portainer:
    image:  portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    depends_on:
      - volume

...
